import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  //로그인한 유저 정보
  let session = await getServerSession(authOptions);
  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="gnb">
            <Link href="/">
              <h1>Wool and only</h1>
            </Link>
            <nav>
              <ul>
                <li>
                  <Link href="/list">List</Link>
                </li>
                <li>
                  <Link href="/write">Write</Link>
                </li>
                <li>
                  <Link href="/register">join</Link>
                </li>
              </ul>
            </nav>
            <div className="icons">
              {session ? (
                <span>
                  {session.user.name}님<LogoutBtn />
                </span>
              ) : (
                <LoginBtn />
              )}
            </div>
          </div>
        </header>
        <div className="container">{children}</div>
        <footer>copyright &copy;plmnko all rights resvered </footer>
      </body>
    </html>
  );
}
